// Code generated by sqlc. DO NOT EDIT.
// source: gambar.sql

package db

import (
	"context"
)

const createGambar = `-- name: CreateGambar :exec
INSERT INTO gambar(
    url, game_id
)VALUES(
    ?,?
)
`

type CreateGambarParams struct {
	Url    string `json:"url"`
	GameID int32  `json:"game_id"`
}

func (q *Queries) CreateGambar(ctx context.Context, arg CreateGambarParams) error {
	_, err := q.db.ExecContext(ctx, createGambar, arg.Url, arg.GameID)
	return err
}

const getGambar = `-- name: GetGambar :one
SELECT url FROM gambar WHERE id =?
`

func (q *Queries) GetGambar(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRowContext(ctx, getGambar, id)
	var url string
	err := row.Scan(&url)
	return url, err
}
