// Code generated by sqlc. DO NOT EDIT.
// source: rating.sql

package db

import (
	"context"
)

const createRating = `-- name: CreateRating :exec
INSERT INTO rating(
    rating, game_id, user_id
)VALUES(
    ?,?,?
)
`

type CreateRatingParams struct {
	Rating int32 `json:"rating"`
	GameID int32 `json:"game_id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) CreateRating(ctx context.Context, arg CreateRatingParams) error {
	_, err := q.db.ExecContext(ctx, createRating, arg.Rating, arg.GameID, arg.UserID)
	return err
}

const updateRating = `-- name: UpdateRating :exec
UPDATE rating SET rating = ?, game_id =?, user_id =? WHERE id =?
`

type UpdateRatingParams struct {
	Rating int32 `json:"rating"`
	GameID int32 `json:"game_id"`
	UserID int32 `json:"user_id"`
	ID     int32 `json:"id"`
}

func (q *Queries) UpdateRating(ctx context.Context, arg UpdateRatingParams) error {
	_, err := q.db.ExecContext(ctx, updateRating,
		arg.Rating,
		arg.GameID,
		arg.UserID,
		arg.ID,
	)
	return err
}
